project-name: sample-spring-boot2
#stack: image-registry.openshift-image-registry.svc:5000/kabanero/skt-spring-boot2:0.3
stack: default-route-openshift-image-registry.apps.hcp.darumtech.net/kabanero/skt-spring-boot2:0.3.24
